name: transefer-indexer
networks:
  - id: 1
    start_block: 22032087
    contracts:
      - name: MyERC20
        address: []
        handler: ./src/EventHandlers.ts
        events:
          - event: Transfer(address indexed from, address indexed to, uint256 value)
            field_selection:
              transaction_fields:
                - hash