name: transefer-indexer
networks:
  - id: 1
    start_block: 22032087
    contracts:
      - name: ERC20
        handler: ./src/EventHandlers.ts
        events:
          - event: Transfer(address indexed from, address indexed to, uint256 value)